name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/wangmi/1es
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
      os: linux
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-10780-Tool
    stages:
      - stage: Stage
        jobs:
          - job: Job_1
            displayName: Build and Sign Azure Plugin for IntelliJ
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                fetchTags: false
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Bash@3
                displayName: Build Utils
                inputs:
                  targetType: inline
                  script: |-
                    mvn -v
                    # ./gradlew buildUtils || exit -1
                    mvn clean install -f ./Utils/pom.xml -T 1C -Dcheckstyle.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
                    mvn clean -f ./Utils/pom.xml
              - task: Bash@3
                displayName: Build Plugin
                inputs:
                  targetType: inline
                  script: |
                    (cd PluginsAndFeatures/azure-toolkit-for-intellij && ./gradlew clean buildPlugin -s -Papplicationinsights.key=$(INTELLIJ_KEY) -PneedPatchVersion=false -Psources=false -Porg.gradle.configureondemand=false -Porg.gradle.daemon=false -Porg.gradle.unsafe.configuration-cache=false -Porg.gradle.caching=false)

                    mkdir -p ./artifacts/intellij/
                    cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/*.zip ./artifacts/intellij/azure-toolkit-for-intellij.zip
                    unzip ./artifacts/intellij/azure-toolkit-for-intellij.zip -d ./artifacts/intellij/folder
                    rm  ./artifacts/intellij/azure-toolkit-for-intellij.zip
              - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@3
                displayName: Sign IntelliJ
                inputs:
                  ConnectedServiceName: vscjavaci_esrp_codesign
                  FolderPath: artifacts/intellij/folder
                  Pattern: azure-toolkit-for-intellij.jar, azure-intellij-plugin-*.jar, azure-intellij-resource-connector-*.jar, azure-toolkit-ide-*.jar, azuretools-core-*.jar,azure-explorer-common-*.jar,hdinsight-node-common-*.jar, azure-sdk-reference-book.jar
                  signConfigType: inlineSignParams
                  inlineOperation: |-
                    [
                            {
                                "KeyCode" : "$(KEY_CODE)",
                                "OperationCode" : "JavaSign",
                                "Parameters" : {
                                    "SigAlg" : "SHA256withRSA",
                                    "Timestamp" : "-tsa http://sha256timestamp.ws.digicert.com/sha256/timestamp"
                                },
                                "ToolName" : "sign",
                                "ToolVersion" : "1.0"
                            },
                            {
                                "KeyCode" : "$(KEY_CODE)",
                                "OperationCode" : "JavaVerify",
                                "Parameters" : {},
                                "ToolName" : "sign",
                                "ToolVersion" : "1.0"
                            }
                    ]
              - task: Bash@3
                displayName: Repackage
                inputs:
                  targetType: inline
                  script: |
                    # Write your commands here

                    (cd ./artifacts/intellij/folder && zip -r ../../azure-toolkit-for-intellij-$(Build.BuildNumber).zip ./azure-toolkit-for-intellij/)
              - task: CopyFiles@2
                displayName: "Copy Files to: $(build.artifactstagingdirectory)"
                inputs:
                  SourceFolder: $(system.defaultworkingdirectory)/artifacts
                  Contents: "*.zip"
                  TargetFolder: $(build.artifactstagingdirectory)
              - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
                displayName: "Manifest Generator "
                inputs:
                  BuildDropPath: $(build.artifactstagingdirectory)
