name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/wangmi/1es
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Ubuntu-2004
      os: linux
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
    customBuildTags:
      - MigrationTooling-mseng-VSJava-11383-Tool
    stages:
      - stage: Stage
        jobs:
          - job: Job_1
            displayName: Build and Sign Azure Plugin for IntelliJ
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(build.artifactstagingdirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                fetchTags: false
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Bash@3
                displayName: Build Toolkit Libs@$(TOOLKIT_BRANCH)
                inputs:
                  targetType: inline
                  script: |-
                    TARGET_BRANCH=$(TOOLKIT_BRANCH)

                    ls ~/.m2/repository/com/microsoft/azure/azure-toolkit-*
                    cd ..
                    git clone https://github.com/microsoft/azure-maven-plugins.git
                    cd azure-maven-plugins/azure-toolkit-libs

                    echo "build azure-toolkit-libs: $TARGET_BRANCH"
                    git fetch origin $TARGET_BRANCH
                    git checkout $TARGET_BRANCH

                    git branch
                    mvn clean install -T 4 -Dmaven.test.skip=true -Dmdep.analyze.skip=true -Dmaven.source.skip=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip -B|| exit -1

                    ls ~/.m2/repository/com/microsoft/azure/azure-toolkit-*
                    echo "cleaning up battlefield."
                    cd ../../
                    rm -rf ./azure-maven-plugins
                    exit 0
              - task: Bash@3
                displayName: Build Utils
                inputs:
                  targetType: inline
                  script: |-
                    mvn -v
                    # ./gradlew buildUtils || exit -1
                    mvn clean install -f ./Utils/pom.xml -T 1C -Dcheckstyle.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
                    mvn clean -f ./Utils/pom.xml
              - task: Bash@3
                displayName: Build Plugin
                inputs:
                  targetType: inline
                  script: |
                    (cd PluginsAndFeatures/azure-toolkit-for-intellij && ./gradlew clean buildPlugin -s -Papplicationinsights.key=$(INTELLIJ_KEY)  -PneedPatchVersion=true -Psources=false -Porg.gradle.configureondemand=false -Porg.gradle.daemon=false -Porg.gradle.unsafe.configuration-cache=false -Porg.gradle.caching=false)

                    mkdir -p ./artifacts/intellij/
                    cp ./PluginsAndFeatures/azure-toolkit-for-intellij/build/distributions/*.zip ./artifacts/intellij/azure-toolkit-for-intellij.zip
                    unzip ./artifacts/intellij/azure-toolkit-for-intellij.zip -d ./artifacts/intellij/folder
                    rm  ./artifacts/intellij/azure-toolkit-for-intellij.zip
              - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5
                displayName: Sign IntelliJ
                condition: and(succeeded(), ne(variables['DisableCodeSign'], 'true'))
                inputs:
                  ConnectedServiceName: 'ESRP-Release-Test'
                  AppRegistrationClientId: '1992ee18-e9d2-42d6-ab20-94dd947a44b6'
                  AppRegistrationTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
                  AuthAKVName: 'vscjavaci'
                  AuthCertName: 'vscjava-esrprelease-auth'
                  AuthSignCertName: 'VSCJava-CodeSign'
                  FolderPath: artifacts/intellij/folder
                  Pattern: azure-intellij-*.jar, azure-toolkit-*.jar, azuretools-core-*.jar,azure-explorer-common-*.jar,hdinsight-node-common-*.jar, azure-sdk-reference-book.jar
                  signConfigType: inlineSignParams
                  inlineOperation: |-
                    [
                            {
                                "KeyCode" : "$(KEY_CODE)",
                                "OperationCode" : "JavaSign",
                                "Parameters" : {
                                    "SigAlg" : "SHA256withRSA",
                                    "Timestamp" : "-tsa http://sha256timestamp.ws.digicert.com/sha256/timestamp"
                                },
                                "ToolName" : "sign",
                                "ToolVersion" : "1.0"
                            },
                            {
                                "KeyCode" : "$(KEY_CODE)",
                                "OperationCode" : "JavaVerify",
                                "Parameters" : {},
                                "ToolName" : "sign",
                                "ToolVersion" : "1.0"
                            }
                    ]
              - task: Bash@3
                displayName: Repackage
                inputs:
                  targetType: inline
                  script: |
                    # Write your commands here

                    (cd ./artifacts/intellij/folder && zip -r ../../azure-toolkit-for-intellij-$(Build.BuildNumber).zip ./azure-toolkit-for-intellij/)
              - task: CopyFiles@2
                displayName: "Copy Files to: $(build.artifactstagingdirectory)"
                inputs:
                  SourceFolder: $(system.defaultworkingdirectory)/artifacts
                  Contents: "*.zip"
                  TargetFolder: $(build.artifactstagingdirectory)
              - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
                displayName: "Manifest Generator "
                inputs:
                  BuildDropPath: $(build.artifactstagingdirectory)
