[versions]
# libraries
# https://search.maven.org/artifact/com.jetbrains.rd/rd-gen
rdGen = "2024.1.1"
opentest4j = "1.3.0"
azureToolkitLibs = "0.47.0"
azureToolkitHdinsightLibs = "0.1.1"
javaWebSocket = "1.5.1"
coroutines = "1.8.0"
ktor = "2.3.12"

# plugins
kotlin = "2.0.10"
serialization = "1.7.1"
changelog = "2.2.1"
intelliJPlatform = "2.0.1"
qodana = "2024.1.9"
aspectj = "8.6"

[libraries]
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
javaWebSocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "javaWebSocket" }
coroutinesReactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "coroutines" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorClientAuth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktorClientWebsockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
azureToolkitLibs = { group = "com.microsoft.azure", name = "azure-toolkit-libs", version.ref = "azureToolkitLibs" }
azureToolkitIdeLibs = { group = "com.microsoft.azure", name = "azure-toolkit-ide-libs", version.ref = "azureToolkitLibs" }
azureToolkitHdinsightLibs = { group = "com.microsoft.hdinsight", name = "azure-toolkit-ide-hdinsight-libs", version.ref = "azureToolkitHdinsightLibs" }
azureToolkitCommonLib = { group = "com.microsoft.azure", name = "azure-toolkit-common-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeCommonLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-common-lib", version.ref = "azureToolkitLibs" }
azureToolkitAuthLib = { group = "com.microsoft.azure", name = "azure-toolkit-auth-lib", version.ref = "azureToolkitLibs" }
azureToolkitAppserviceLib = { group = "com.microsoft.azure", name = "azure-toolkit-appservice-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeAppserviceLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-appservice-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeContainerregistryLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-containerregistry-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeArmLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-arm-lib", version.ref = "azureToolkitLibs" }
azureToolkitDatabaseLib = { group = "com.microsoft.azure", name = "azure-toolkit-database-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeDatabaseLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-database-lib", version.ref = "azureToolkitLibs" }
azureToolkitMysqlLib = { group = "com.microsoft.azure", name = "azure-toolkit-mysql-lib", version.ref = "azureToolkitLibs" }
azureToolkitSqlserverLib = { group = "com.microsoft.azure", name = "azure-toolkit-sqlserver-lib", version.ref = "azureToolkitLibs" }
azureToolkitPostgreLib = { group = "com.microsoft.azure", name = "azure-toolkit-postgre-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeApplicationinsightsLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-applicationinsights-lib", version.ref = "azureToolkitLibs" }
azureToolkitKeyvaultLib = { group = "com.microsoft.azure", name = "azure-toolkit-keyvault-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeKeyvaultLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-keyvault-lib", version.ref = "azureToolkitLibs" }
azureToolkitRedisLib = { group = "com.microsoft.azure", name = "azure-toolkit-redis-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeRedisLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-redis-lib", version.ref = "azureToolkitLibs" }
azureToolkitStorageLib = { group = "com.microsoft.azure", name = "azure-toolkit-storage-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdeStorageLib = { group = "com.microsoft.azure", name = "azure-toolkit-ide-storage-lib", version.ref = "azureToolkitLibs" }
azureToolkitIdentityLib = { group = "com.microsoft.azure", name = "azure-toolkit-identity-lib", version.ref = "azureToolkitLibs" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
aspectj = { id = "io.freefair.aspectj.post-compile-weaving", version.ref = "aspectj" }
